### ISSUE TITLE
OpenCV dilate, errode error

### ISSUE THREAD

**Issue by fpetric** [maloL/nao-fsm#1]
There is an issue with different versions of OpenCV which occurs when calling erode and dilate functions.

This error is observed in OpenCV 2.3.1:
cv2.error: /build/buildd/opencv-2.3.1/modules/imgproc/src/morph.cpp:866: error: (-213) Unsupported data type (=6) in function getMorphologyRowFilter

Lines producing the error are lines 173 and 174 in NaoImageProcessing.py:
 dest=cv2.dilate(dest   *1.0, np.ones((10,10)))
 dest=cv2.erode(dest   *1.0, np.ones((10,10)))

An educated guess would be that multiplying by 1.0 does not convert dest to an appropriate type for dilate and erode functions.

**Comment by fpetric** [comment]
Quick fix:
dest=cv2.dilate((dest *1.0).astype(np.float32),np.ones((10,10)))
dest=cv2.erode((dest *1.0).astype(np.float32),np.ones((10,10)))

**Comment by fpetric** [comment]
Luka, this is also no longer an issue?

**Comment by maloL** [comment]
Never had this error myself, so i think it is resolved. I added to documentation that prefered version of opencv is 2.4.9

**Comment by fpetric** [comment]
I am marking it as resolved and closing it
