### ISSUE TITLE
Program fails to cleanup after finishing

### ISSUE THREAD

**Issue by fpetric** [maloL/nao-fsm#2]
After the gesture is recognized, program exits but the object tracking via head movements is still enabled, and gesture recognition is still running.

ObjectTrackerModule in NAO_fsm.py has the unload method which is never called, which may be the problem.

**Comment by maloL** [comment]
Unload method has been added, there is no more unwanted object tracking.

**Comment by fpetric** [comment]
Luka, is this issue resolved?
